---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: hardeningcentos8
    box: centos/8
    box_version: 1905.1
    memory: 4096
    cpus: 4
    provision: true
  - name: hardeningdebian10
    box: debian/buster64
    box_version: 10.3.0
    memory: 4096
    cpus: 4
    provision: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
